### ISSUE TITLE
Support for Waltti routes

### ISSUE THREAD

**Issue by alehuo** [Mallonbacka/custom-component-digitransit#54]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Currently the custom component doesn't support Waltti routes. This is easy to implement, as the GraphQL route URL is a bit different from that of HSL, e.g. https://api.digitransit.fi/routing/v1/routers/waltti/index/graphql instead of https://api.digitransit.fi/routing/v1/routers/hsl/index/graphql

### Describe the solution you'd like

Make it possible to choose between HSL and Waltti for routes and timetables.

### Describe alternatives you've considered

Forking the repo to modify the code from HSL to Waltti, but I feel like it would serve more people to just modify the GraphQL client to take into account other vendors, such as Waltti.

### Additional context

-

**Comment by Mallonbacka** [comment]
Hello,
Thanks for sharing this. The original design used the generic national digitransit endpoints, which combine lots of regions' data and worked for most things, but were missing a few HSL-specific bits of data, which is why I switched it over to use the HSL-only endpoints in the most recent version.

Ideally, we could just use national endpoints with no problems, but that doesn't seem feasible at the moment. 

I've not tried the Waltti-specific endpoint at all yet, and you're quite right that it's probably possible to offer those two with minimal work, and meet the needs of a lot of users beyond the capital region. 

I'll try it, hopefully this week, and post an update here.

**Comment by Mallonbacka** [comment]
Hello again,
This was quite straightforward, so I went ahead and released `v0.3.0`, which adds support for Waltti stops. From testing, it seems like only the GTFS ID works for these stops (get this from the Reittiopas stop page URL, as described in the README). 

I'm planning to refactor the config flow a little in connection with Station support, so hopefully the onboarding process can be improved soon. 

Feel free to reply here, or open a new issue, if you have any trouble getting it set up.
